### ISSUE TITLE
finetuning config on a40×4

### ISSUE THREAD

**Issue by CCCarloooo** [luohongyin/SAIL#5]
Hello, I am reproducing your experiment. I have used your settings on my four a40. However, my training duration is around 90 hours, which is much higher than the 24 hours mentioned in your paper.
i use torchrun as my launcher. just replace the `accelerate launch` with `torchrun --nproc_per_node=4`.
Maybe I have made mistakes in my experiment configuration or it could be due to the usage of Llama2.
 thank you!

**Comment by CCCarloooo** [comment]
I tried `llama1`, but it still shows that 85 hours of training are required.

**Comment by luohongyin** [comment]
Thanks for asking! what is your batchsize per device? Here's my complete deepspeed config:
```yaml
compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  gradient_accumulation_steps: 16
  gradient_clipping: 1.0
  offload_optimizer_device: cpu
  offload_param_device: cpu
  zero3_init_flag: false
  zero_stage: 2
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```
